### ISSUE TITLE
Incompatibility with JEI + Create [1.16.5].

### ISSUE THREAD

**Issue by LoSilopante** [SmileycorpMC/Blood-Smeltery#2]
Using this mod alongside [Create](https://www.curseforge.com/minecraft/mc-mods/create) and [JustEnoughItems](https://www.curseforge.com/minecraft/mc-mods/jei) causes all custom processing recipes from Create's devices to not be visible through JEI.

The modlist is as follows:
[Forge 36.2.35 for Minecraft 1.16.5]
- Blood Smeltery    1.1.3
- create                  v0.3.2g
- flywheel               0.2.5
- jei                        7.7.1.152
- Mantle                1.6.157
- Patchouli             53.3

**Comment by LoSilopante** [comment]
[Mention] https://github.com/Creators-of-Create/Create/issues/3161

**Comment by SmileycorpMC** [comment]
The current release of bloodsmeltery 1.16 shouldn't even have an enabled jei plugin, which shouldn't affect anything to do with create's JEI plugin, can you send the debug.log, so I can see if anything is going on?

**Comment by SmileycorpMC** [comment]
I've found the issue and it doesn't seem to be present in the current dev build, which should be released soon.

**Comment by LoSilopante** [comment]
Here it is: [latest.log](https://github.com/SmileycorpMC/Blood-Smeltery/files/9041708/latest.log)

**Comment by SmileycorpMC** [comment]
Should be fixed as of release 1.1.4.
