### ISSUE TITLE
[1.18.2] Latest update (1.1.5) causes items not to stack in existing stacks upon picking new ones up.

### ISSUE THREAD

**Issue by Gbergz** [SmileycorpMC/Blood-Smeltery#4]
Title^

**Issues/Reproduce:** 
Grab a few dirt from the creative menu, go into survival. Mine some grass, pick up dirt.
Blocks are not stacking.

Appears the items not stacking are given an empty Nbt Value, that is why they refuse stack.

**Versions:** (these are the only mods I have.)
Patchouli-1.18.2-71.1
TConstruct-1.18.2-3.5.2.40
BloodMagic-1.18.2-3.2.6-41
Blood-Smeltery-1.18.2-1.1.5
Mantle-1.18.2-1.9.27

**Minecraft**: 1.18.2
**Forge**: 40.1.80

Update in question: [1.1.5](https://www.curseforge.com/minecraft/mc-mods/blood-smeltery/files/4002074)

[1.1.4a](https://www.curseforge.com/minecraft/mc-mods/blood-smeltery/files/3911467) works as normal, no stacking issues.

**Video showing the issue**:
https://www.youtube.com/watch?v=YmTJrfhUnBQ

**-** Gbergz

**Comment by SmileycorpMC** [comment]
Huh looks like it's a weird issue with how tinkers handles it's tools, I've found the issue so as long as I check if the item is a tool or not before using tinkers code that should fix it.

Should be fully fixed later today.

**Comment by SmileycorpMC** [comment]
Should be fixed as of version 1.1.5a.
