### ISSUE TITLE
Tool part colors are currently broken

### ISSUE THREAD

**Issue by notWaterGuy12** [SmileycorpMC/Blood-Smeltery#5]
The items themselves render right, but when used to make a tool they turn white instead of retaining their colors.

**Comment by SmileycorpMC** [comment]
Which version are you using and what other mods do you have installed?

**Comment by notWaterGuy12** [comment]
Mod version 1.1.5a, forge version 40.2.0
After a little testing, it seems to occur when Rubidium is present

**Comment by SmileycorpMC** [comment]
After looking into it there's nothing that can be done on my end, it's an issue caused by a bug in rubidium, that seems to be affecting quite a few other tinkers addons as well as some other mods.

**Comment by notWaterGuy12** [comment]
Did a little digging, looks like there is a workaround:
https://github.com/Asek3/Rubidium/issues/166#issuecomment-1292758497
